class ConfigDefaults {
  // Inventory only: membership does not imply that the corresponding Java
  // control or runtime behavior has already been ported.
  static const Set<String> javaRuntimeKeys = {
    'album_titles.save',
    'auto.update',
    'chans.chan_sites',
    'clipboard.autorip',
    'cookies.*',
    'derpi.key',
    'descriptions.save',
    'DeviantartCustomLoginPassword',
    'DeviantartCustomLoginUsername',
    'download.history',
    'download.max_size',
    'download.retries',
    'download.retry.sleep',
    'download.save_order',
    'download.show_popup',
    'download.timeout',
    'e621.cookies',
    'e621.useragent',
    'enable.finish.command',
    'erome.laravel_session',
    'error.skip404',
    'errors.skip404',
    'file.overwrite',
    'finish.command',
    'furaffinity.cookies',
    'furaffinity.login',
    'hentai-foundry.filter_order',
    'hentai-foundry.use_prefix',
    'history.end_rip_after_already_seen',
    'history.location',
    'history.warn_before_delete',
    'imgur.client_id',
    'instagram.download_images_only',
    'instagram.session_id',
    'lang',
    'log.level',
    'log.save',
    'page.timeout',
    'play.sound',
    'prefer.mp4',
    'proxy.http',
    'proxy.socks',
    'queue',
    'reddit.max_upvotes',
    'reddit.min_upvotes',
    'reddit.rip_by_upvote',
    'reddit.use_sub_dirs',
    'remember.url_history',
    'rips.directory',
    'security.check_update_hash',
    'ssl.verify.off',
    'testing.always_try_to_update',
    'threads.size',
    'tumblr.auth',
    'twitter.auth',
    'twitter.exclude_replies',
    'twitter.max_items_request',
    'twitter.max_requests',
    'twitter.rip_retweets',
    'urls_only.save',
    'window.h',
    'window.position',
    'window.w',
    'window.x',
    'window.y',
  };

  static const Map<String, int> integers = {
    'threads.size': 5,
    'download.retries': 3,
    'download.timeout': 60000,
    'page.timeout': 5000,
    'download.max_size': 104857600,
    'download.retry.sleep': 5000,
    'twitter.max_requests': 10,
    'reddit.min_upvotes': 0,
    'reddit.max_upvotes': 10000,
    'history.end_rip_after_already_seen': 1000000000,
    'proxy.port': 8080,
  };

  static const Map<String, bool> booleans = {
    'file.overwrite': false,
    'error.skip404': true,
    'errors.skip404': false,
    'download.save_order': true,
    'download.show_popup': false,
    'album_titles.save': true,
    'twitter.rip_retweets': false,
    'twitter.exclude_replies': true,
    'clipboard.autorip': false,
    'reddit.rip_by_upvote': false,
    'reddit.use_sub_dirs': true,
    'remember.url_history': true,
    'history.skip_downloaded_urls': true,
    'history.warn_before_delete': true,
    'ssl.verify.off': false,
    'urls_only.save': false,
    'play.sound': false,
    'prefer.mp4': false,
    'proxy.enabled': false,
  };

  static const Map<String, String> strings = {
    'download.ignore_extensions': '',
    'twitter.auth':
        'VW9Ybjdjb1pkd2J0U3kwTUh2VXVnOm9GTzVQVzNqM29LQU1xVGhnS3pFZzhKbGVqbXU0c2lHQ3JrUFNNZm8=',
    'tumblr.auth': 'JFNLu3CbINQjRdUvZibXW9VpSEVYYtiPJ86o8YmvgLZIoKyuNX',
    'tsumino.blacklist.tags': '',
    'gw.api': 'gonewild',
    'erome.laravel_session': '',
    'proxy.host': '',
    'proxy.username': '',
    'proxy.password': '',
    'cookies.reddit.com': '',
    'cookies.imgur.com': '',
    'cookies.erome.com': '',
    'cookies.soundgasm.net': '',
    'cookies.vidble.com': '',
  };
}
